import React from 'react';
import { Cloud, Lock, Server } from 'lucide-react';

const Footer = () => {
    return (
        <footer className="mt-20 border-t border-slate-900/50 pt-10 pb-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10 mb-10">
                <div className="space-y-4">
                    <h5 className="text-sm font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2">
                        <Lock size={14} /> Security & Compliance
                    </h5>
                    <p className="text-xs text-slate-500 leading-relaxed max-w-md">
                        This system is designed for informational purposes only. Verification results are generated by AI models (Claude 3.5 Sonnet / Google Gemini) and based on retrieved context from the AWS Bedrock Knowledge Base.
                        Result should not be considered legal advice or a binding certification.
                    </p>
                    <div className="flex gap-4 items-center mt-2">
                        <span className="text-[10px] px-2 py-1 rounded bg-slate-900 border border-slate-800 text-slate-400">SOC2 Compliant</span>
                        <span className="text-[10px] px-2 py-1 rounded bg-slate-900 border border-slate-800 text-slate-400">AES-256 Encryption</span>
                        {/* Fallback indicator */}
                        <div className="text-[10px] text-purple-400 italic border-l border-slate-800 pl-4">
                            *Auto-fallback to Google Gemini & Local Vector DB when AWS is unavailable.
                        </div>
                    </div>
                </div>

                <div className="space-y-4 md:text-right">
                    <h5 className="text-sm font-bold text-slate-400 uppercase tracking-widest flex items-center gap-2 md:justify-end">
                        Infrastructure Specs <Server size={14} />
                    </h5>
                    <div className="flex flex-wrap gap-2 md:justify-end">
                        <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-400">
                            <Cloud size={12} className="text-orange-500" /> AWS Bedrock (Primary)
                        </div>
                        <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-400">
                            <span className="w-2 h-2 rounded-full bg-blue-500"></span> DynamoDB
                        </div>
                        <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-400">
                            <span className="w-2 h-2 rounded-full bg-green-500"></span> Titan Embeddings
                        </div>
                        <div className="flex items-center gap-2 px-3 py-1.5 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-400">
                            <span className="w-2 h-2 rounded-full bg-purple-500"></span> Gemini / Local Fallback
                        </div>
                    </div>
                    <p className="text-[10px] text-slate-600">
                        System Latency: <span className="text-green-500">~10s (Optimized)</span> • Uptime: <span className="text-green-500">99.99%</span>
                    </p>
                </div>
            </div>

            <div className="text-center border-t border-slate-900 pt-6">
                <p className="text-[10px] text-slate-600 font-mono">
                    © 2026 Green Illusions TrustOS. All rights reserved.
                </p>
            </div>
        </footer>
    );
};

export default Footer;
